site_name: Teampass Documentation
site_author: Nils Laumaillé
copyright: '2016 (c) Nils Laumaillé - Teampass.net'
theme: slate
pages:
- Home: 'index.md'
- Definitions: 'definition.md'
- Installation:
    - 'On Linux server': 'install/install-linux.md'
    - 'On Windows server': 'install/install-windows.md'
    - 'Initial setup': 'install/setup.md'
    - 'Upgrade': 'install/upgrade.md'
- Manage:
    - 'Folders': 'manage/manage-folders.md'
    - 'Groups': 'manage/manage-groups.md'
    - 'Users': 'manage/manage-users.md'
- API:
    - 'Reading items': 'api/api-read.md'
    - 'Writing items': 'api/api-write.md'
    - 'Miscellaneous': 'api/api-special.md'
- Teampass-Connect:
    - 'Usage': 'tpc/index.md'
- FAQ: 'faq.md'
