site_name: Teampass Documentation
site_author: Nils Laumaillé
copyright: '2017 © Nils Laumaillé - Teampass.net'

repo_url: https://github.com/nilsteampassnet/teampass_doc/

theme: readthedocs
theme_dir: 'docs/custom_theme/'

extra_javascript:
- js/extra.js

pages:
- Home: 'index.md'
- Intro: 'GUI.md'
- Features:
    - 'Items': 'features/feat-items.md'
    - 'Authentication': 'features/feat-2FA.md'
    - 'Custom fields': 'features/feat-custf.md'
    - 'Suggestion': 'features/feat-sug.md'
    - 'Offline mode': 'features/feat-offline.md'
    - 'Expiration': 'features/feat-expi.md'
    - 'Encryption': 'features/feat-encrypt.md'
    - 'Import & Export': 'features/feat-impexp.md'
    - 'Remote server': 'features/feat-remote.md'
    - 'Folders': 'features/feat-folders.md'
    - 'User profile': 'features/feat-prof.md'
- Installation:
    - 'On Linux server': 'install/install-linux.md'
    - 'On Windows server': 'install/install-windows.md'
    - 'Initial setup': 'install/setup.md'
    - 'Upgrade': 'install/upgrade.md'
    - 'Advanced setup': 'install/ldap.md'
- Manage:
    - 'Folders': 'manage/manage-folders.md'
    - 'Groups': 'manage/manage-groups.md'
    - 'Users': 'manage/manage-users.md'
    - 'Options': 'manage/misc-options.md'
- Help:
    - 'Common Questions': 'faq.md'
    - 'Common Errors': 'errors.md'
- API:
    - 'Reading items': 'api/api-read.md'
    - 'Writing items': 'api/api-write.md'
    - 'Miscellaneous': 'api/api-special.md'
- Teampass-Connect:
    - 'Overview': 'tpc/index.md'
    - 'Installation': 'tpc/install.md'
    - 'Usage': 'tpc/usage.md'
