site_name: Teampass
pages:
- Home: 'index.md'
- API:
    - 'Reading items': 'api/api-read.md'
    - 'Writing items': 'api/api-write.md'
- Teampass-Connect:
    - 'Usage': 'tpc/index.md'
- FAQ: 'faq.md'
